steps:
  # Ngambil data env yg disimpen di cloud storage pake gsuri
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "be/.env"]

  # BARU: Ngambil data account-key.json yg disimpen di cloud storage pake gsuri
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ACCOUNT_KEY_PATH_GCS}", "be/account-key.json"] # Asumsi disimpan di direktori 'be'

  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/fam07", "."]
    dir: "be"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fam07"]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "fam07",
        "--image",
        "gcr.io/$PROJECT_ID/fam07",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY